spring.application.name=web
spring.datasource.url=jdbc:mysql://localhost:3306/actividades_db
spring.datasource.username=root
spring.datasource.password=Terres1009.


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tamaño máximo por archivo
spring.servlet.multipart.max-file-size=50MB

# Tamaño máximo total por request
spring.servlet.multipart.max-request-size=50MB
